import React, { useState } from "react";
import { GeneratedPoA, UploadedFile } from "../types";
import { 
  FileText, Check, Copy, RefreshCw, Sparkles, UserCheck, 
  Download, AlertTriangle, ChevronRight, FileDown, ArrowLeft, Printer, ShieldCheck
} from "lucide-react";

interface PoaReviewProps {
  poa: GeneratedPoA;
  onBack: () => void;
  onRegenerate: (adjustments: string) => Promise<void>;
  loading: boolean;
  uploadedFiles: UploadedFile[];
  emailText: string;
  onStartRefine?: (poaText: string) => void;
}

export default function PoaReview({
  poa,
  onBack,
  onRegenerate,
  loading,
  uploadedFiles,
  emailText,
  onStartRefine
}: PoaReviewProps) {
  const [copied, setCopied] = useState<boolean>(false);
  const [polishText, setPolishText] = useState<string>("");
  const [activeTab, setActiveTab] = useState<"en" | "zh">("en");

  // Helper to clean up standard letter header if generated by AI (slices everything before the salutation)
  const cleanPoaMarkdown = (markdown: string): string => {
    const match = markdown.match(/(?:^|\n)\s*(Dear|To\s+the|To\s+Amazon|亲爱的|尊敬的|致)\s+/i);
    if (match && match.index !== undefined) {
      const startIndex = markdown.indexOf(match[1], match.index);
      return markdown.substring(startIndex).trim();
    }
    return markdown.trim();
  };

  const cleanedPoaEn = cleanPoaMarkdown(poa.poaMarkdown);
  const cleanedPoaZh = cleanPoaMarkdown(poa.poaMarkdownZh || "");
  const currentPoa = activeTab === "en" ? cleanedPoaEn : cleanedPoaZh;

  const handleCopy = () => {
    navigator.clipboard.writeText(currentPoa);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePolish = async () => {
    if (!polishText.trim() && !loading) return;
    await onRegenerate(polishText);
  };

  const handleDownloadTxt = () => {
    const element = document.createElement("a");
    const file = new Blob([currentPoa], { type: "text/plain;charset=utf-8" });
    element.href = URL.createObjectURL(file);
    element.download = activeTab === "en" 
      ? "Amazon_Appeal_Plan_of_Action_EN.md" 
      : "Amazon_Appeal_Plan_of_Action_ZH.md";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      alert("请允许弹出窗口以打印或另存为 PDF！");
      return;
    }

    const title = activeTab === "en" 
      ? "Amazon Seller Performance - Plan of Action" 
      : "亚马逊卖家绩效团队 - 申诉信 (Plan of Action)";

    const contentHtml = `
      <html>
        <head>
          <title>${title}</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              color: #1a1a1a;
              line-height: 1.6;
              padding: 40px;
              max-width: 800px;
              margin: 0 auto;
            }
            h1, h2, h3 {
              color: #0f172a;
              border-bottom: 1px solid #e2e8f0;
              padding-bottom: 8px;
              margin-top: 24px;
            }
            h1 {
              font-size: 24px;
              text-align: center;
              margin-bottom: 30px;
              border-bottom: 2px solid #0f172a;
            }
            h2 {
              font-size: 18px;
            }
            p {
              font-size: 14px;
              margin-bottom: 16px;
            }
            ul, ol {
              font-size: 14px;
              margin-bottom: 16px;
              padding-left: 20px;
            }
            li {
              margin-bottom: 8px;
            }
            strong {
              color: #000;
            }
            .footer-info {
              margin-top: 50px;
              border-top: 1px solid #e2e8f0;
              padding-top: 15px;
              font-size: 12px;
              color: #64748b;
              text-align: center;
            }
            @media print {
              body {
                padding: 20px;
              }
              button {
                display: none;
              }
            }
          </style>
        </head>
        <body>
          <div>
            ${currentPoa
              .replace(/\r/g, "")
              .replace(/^### (.*)/gm, "<h3>$1</h3>")
              .replace(/^## (.*)/gm, "<h2>$1</h2>")
              .replace(/^# (.*)/gm, "<h1>$1</h1>")
              .replace(/^\s*[-*]\s+(.*)/gm, "<li>$1</li>")
              .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
              .replace(/\n/g, "<br>")}
          </div>

          <script>
            window.onload = function() {
              window.print();
            }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(contentHtml);
    printWindow.document.close();
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
      {/* Left 7 Columns: PoA Preview & Interactive Polish */}
      <div className="lg:col-span-8 bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl text-slate-100 flex flex-col gap-6">
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="bg-emerald-500/10 text-emerald-400 p-2 rounded-lg">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <h3 className="font-semibold text-lg text-slate-100">
                第三步：AI 智能 PoA 申诉信初稿
              </h3>
              <p className="text-xs text-slate-400">已结合您的调研答案及最佳申诉例库</p>
            </div>
          </div>

          <div className="flex bg-slate-950 p-1 rounded-lg border border-slate-800">
            <button
              onClick={() => setActiveTab("en")}
              className={`text-[11px] font-medium px-3 py-1.5 rounded-md transition-colors ${
                activeTab === "en"
                  ? "bg-slate-800 text-teal-400"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              英文版
            </button>
            <button
              onClick={() => setActiveTab("zh")}
              className={`text-[11px] font-medium px-3 py-1.5 rounded-md transition-colors ${
                activeTab === "zh"
                  ? "bg-slate-800 text-teal-400"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              中文版
            </button>
          </div>
        </div>

        {/* Core Markdown Preview Area */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 overflow-y-auto max-h-[500px] relative font-sans">
          <div className="text-xs text-slate-300 leading-relaxed whitespace-pre-wrap selection:bg-teal-500/20 selection:text-teal-300">
            {currentPoa}
          </div>

          {/* Floater overlay actions */}
          <div className="absolute top-3 right-3 flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-1.5 bg-slate-900 border border-slate-800 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-slate-100 transition-colors flex items-center gap-1.5 text-[10px]"
              title="复制到剪贴板"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-400" />
                  已复制
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  复制
                </>
              )}
            </button>
          </div>
        </div>

        {/* Step 4: Expert/Provider Adjustments / Manual Polish Input */}
        <div className="border-t border-slate-800/80 pt-5 flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4.5 w-4.5 text-teal-400" />
            <h4 className="text-xs font-bold text-slate-200 uppercase tracking-wider">
              (可选) 服务商专家人工审核 / 一键高保真润色
            </h4>
          </div>

          <p className="text-[11px] text-slate-400 leading-relaxed">
            作为申诉服务商，您可以根据店铺历史数据在此输入您的调整指示、补充具体的发票信息、说明相关退件物流凭证，或者指定修改某些措辞。AI 将根据您的指示重新润色 Plan of Action。
          </p>

          <div className="flex gap-2">
            <input
              type="text"
              value={polishText}
              onChange={(e) => setPolishText(e.target.value)}
              placeholder="例如：'补充发票号码为 VAT-2026-98721，并微调纠正行动中关于库存销毁数量的叙述，语气再诚恳一点'"
              className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-teal-500"
            />
            <button
              onClick={handlePolish}
              disabled={loading || !polishText.trim()}
              className={`px-4.5 py-2.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all shrink-0 ${
                !polishText.trim()
                  ? "bg-slate-800 text-slate-500 cursor-not-allowed"
                  : loading
                    ? "bg-teal-500/20 text-teal-400 border border-teal-500/30 cursor-wait"
                    : "bg-teal-500 text-slate-950 hover:opacity-95 shadow-md shadow-teal-500/10 cursor-pointer"
              }`}
            >
              {loading ? (
                <RefreshCw className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Sparkles className="h-3.5 w-3.5" />
              )}
              一键精细润色
            </button>
          </div>
        </div>

        {/* Appeal rejected entry banner */}
        {onStartRefine && (
          <div className="border-t border-slate-800/85 pt-5 flex flex-col sm:flex-row items-center justify-between gap-4 bg-slate-950/40 p-4.5 rounded-xl border border-slate-800/60">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
              <div className="flex flex-col gap-0.5">
                <span className="text-xs font-bold text-slate-200">申诉不幸被拒绝？</span>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  如果亚马逊驳回了这份 POA，请不要慌张。点击右侧按钮导入亚马逊最新的拒绝信/退件通知，AI 将针对性地为您诊断并完善申诉内容！
                </p>
              </div>
            </div>
            <button
              onClick={() => onStartRefine(cleanedPoaEn)}
              className="px-4 py-2 bg-amber-500/10 border border-amber-500/25 hover:bg-amber-500/20 text-amber-300 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer flex items-center gap-1.5"
            >
              <RefreshCw className="h-3.5 w-3.5" />
              继续完善被拒 POA
            </button>
          </div>
        )}

        {/* Quick action footer */}
        <div className="flex items-center justify-between border-t border-slate-800 pt-5">
          <button
            onClick={onBack}
            className="px-5 py-2.5 rounded-xl border border-slate-800 hover:bg-slate-800/40 text-slate-400 hover:text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-all"
          >
            <ArrowLeft className="h-4 w-4" />
            重新收集证据
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadTxt}
              className="px-4 py-2.5 bg-slate-950 border border-slate-800 hover:border-slate-700 text-slate-300 hover:text-slate-100 rounded-xl text-xs font-medium flex items-center gap-1.5 transition-colors"
            >
              <FileDown className="h-4 w-4 text-slate-400" />
              导出 TXT (Markdown)
            </button>

            <button
              onClick={handlePrint}
              className="px-5 py-2.5 bg-gradient-to-r from-teal-500 to-emerald-500 text-slate-950 rounded-xl text-xs font-bold flex items-center gap-1.5 hover:opacity-95 shadow-lg shadow-teal-500/15 cursor-pointer"
            >
              <Printer className="h-4 w-4" />
              生成标准 PDF 格式并下载
            </button>
          </div>
        </div>
      </div>

      {/* Right 4 Columns: Expert Audit Suggestions & Checked Evidence */}
      <div className="lg:col-span-4 flex flex-col gap-6">
        {/* Expert Checklist */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl text-slate-100">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-3 mb-4">
            <UserCheck className="h-4.5 w-4.5 text-teal-400" />
            <h4 className="font-semibold text-sm">专家风控提交建议 (Service Audit)</h4>
          </div>

          <ul className="space-y-3">
            {poa.expertAuditSuggestions.map((suggestion, idx) => (
              <li key={idx} className="flex items-start gap-2.5 text-xs text-slate-300 leading-relaxed">
                <ChevronRight className="h-4 w-4 text-teal-400 shrink-0 mt-0.5" />
                <span>{suggestion}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Checked Evidence / Document Attachment Checklist */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl text-slate-100">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-3 mb-3">
            <ShieldCheck className="h-4.5 w-4.5 text-emerald-400" />
            <h4 className="font-semibold text-sm">已打包上传证明材料 ({uploadedFiles.length})</h4>
          </div>

          {uploadedFiles.length > 0 ? (
            <div className="flex flex-col gap-2 max-h-[160px] overflow-y-auto">
              {uploadedFiles.map((f) => (
                <div key={f.id} className="bg-slate-950 p-2.5 rounded-lg border border-slate-800/80 flex items-center justify-between text-xs">
                  <div className="flex items-center gap-2 text-slate-300 min-w-0">
                    <FileText className="h-4 w-4 text-emerald-500 shrink-0" />
                    <span className="font-medium truncate" title={f.name}>{f.name}</span>
                  </div>
                  <span className="text-[10px] text-slate-500 bg-slate-900 px-1.5 py-0.5 rounded shrink-0">{f.size}</span>
                </div>
              ))}
              <p className="text-[10px] text-slate-400 mt-2 leading-relaxed">
                💡 **提交建议：** 在亚马逊后台上传申诉信时，请务必在附件中 **连同上述这些高还原证据文件** 一并打包上传。
              </p>
            </div>
          ) : (
            <div className="py-4 text-center text-slate-500 flex flex-col items-center justify-center gap-1.5">
              <AlertTriangle className="h-8 w-8 text-amber-500/40" />
              <p className="text-xs">未上传任何支持材料作为佐证附件</p>
              <p className="text-[10px] text-slate-500 leading-normal max-w-[200px]">
                空无证据的申诉很难获得通过，极力建议返回上一步在问卷栏处上传证明材料文件。
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
